CREATE TABLE IF NOT EXISTS `Hint` (`imageUrl` TEXT, `text` TEXT, `questId` INTEGER NOT NULL, `index` INTEGER NOT NULL, PRIMARY KEY(`questId`, `index`), FOREIGN KEY(`questId`) REFERENCES `Quest`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE );

CREATE TABLE IF NOT EXISTS `Quest` (`latitude` REAL NOT NULL, `longitude` REAL NOT NULL, `radius` REAL NOT NULL, `missionId` INTEGER NOT NULL, `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, FOREIGN KEY(`missionId`) REFERENCES `Mission`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE );
CREATE INDEX IF NOT EXISTS `index_Quest_missionId` ON `Quest` (`missionId`);

CREATE TABLE IF NOT EXISTS `Mission` (`title` TEXT NOT NULL, `difficulty` TEXT NOT NULL, `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL);

CREATE TABLE IF NOT EXISTS `Playtrough` (`active` INTEGER NOT NULL, `startedAt` TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, `missionId` INTEGER NOT NULL, `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, FOREIGN KEY(`missionId`) REFERENCES `Mission`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE );
CREATE INDEX IF NOT EXISTS `index_Playtrough_missionId` ON `Playtrough` (`missionId`);

CREATE TABLE IF NOT EXISTS room_master_table (id INTEGER PRIMARY KEY,identity_hash TEXT);
INSERT OR REPLACE INTO room_master_table (id,identity_hash) VALUES(42, '74ecb9f45e4ad7222c5bda47410c4b48');